wandb: Starting wandb agent üïµÔ∏è
2023-05-03 19:21:08,715 - wandb.wandb_agent - INFO - Running runs: []
2023-05-03 19:21:09,153 - wandb.wandb_agent - INFO - Agent received command: run
2023-05-03 19:21:09,153 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	discount_factor: 0.5760788269659016
	epsilon_decay: 0.9990509629298024
	frame_repeat: 16
	lr: 0.049586024056473825
	memory_size: 10000
	steps_per_epoch: 3000
2023-05-03 19:21:09,159 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python sweep.py --batch_size=32 --discount_factor=0.5760788269659016 --epsilon_decay=0.9990509629298024 --frame_repeat=16 --lr=0.049586024056473825 --memory_size=10000 --steps_per_epoch=3000
2023-05-03 19:21:14,176 - wandb.wandb_agent - INFO - Running runs: ['ei9fc682']
wandb: Currently logged in as: ugo1 (fuzzy-enigma). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.1
wandb: Run data is saved locally in /scratch/ugo1/fuzzy-enigma/wandb/run-20230503_192119-ei9fc682
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run efficient-sweep-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep
wandb: üßπ View sweep at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/sweeps/7trn9eh4
wandb: üöÄ View run at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/runs/ei9fc682
Using device=cuda ...
Creating game environment ...
Game environment initialized ...
Creating new agent ...


Epoch #1
	Results (Train): mean: -235.5 +/- 128.5, min: -360.0, max: 62.0,
	Results (Test): mean: -276.0 +/- 81.7, min: -310.0 max: 62.0
Total elapsed time: 2.57 minutes


Epoch #2
	Results (Train): mean: -270.8 +/- 83.9, min: -315.0, max: 62.0,
	Results (Test): mean: -262.8 +/- 93.8, min: -315.0 max: 62.0
Total elapsed time: 5.11 minutes


Epoch #3
	Results (Train): mean: -280.4 +/- 76.1, min: -320.0, max: 62.0,
	Results (Test): mean: -262.3 +/- 95.1, min: -315.0 max: 62.0
Total elapsed time: 7.51 minutes


Epoch #4
	Results (Train): mean: -266.5 +/- 94.7, min: -320.0, max: 62.0,
	Results (Test): mean: -290.6 +/- 60.9, min: -325.0 max: 30.0
Total elapsed time: 9.92 minutes


Epoch #5
	Results (Train): mean: -272.9 +/- 87.3, min: -320.0, max: 62.0,
	Results (Test): mean: -286.2 +/- 63.4, min: -315.0 max: -2.0
Total elapsed time: 12.34 minutes


Epoch #6
	Results (Train): mean: -265.5 +/- 99.3, min: -315.0, max: 62.0,
	Results (Test): mean: -272.6 +/- 80.0, min: -315.0 max: 30.0
Total elapsed time: 14.72 minutes


Epoch #7
	Results (Train): mean: -274.2 +/- 86.0, min: -320.0, max: 62.0,
	Results (Test): mean: -283.7 +/- 70.7, min: -320.0 max: -2.0
Total elapsed time: 17.14 minutes


Epoch #8
	Results (Train): mean: -280.3 +/- 73.3, min: -320.0, max: 46.0,
	Results (Test): mean: -270.4 +/- 85.0, min: -315.0 max: 46.0
Total elapsed time: 19.53 minutes


Epoch #9
	Results (Train): mean: -269.1 +/- 91.7, min: -320.0, max: 62.0,
	Results (Test): mean: -263.5 +/- 89.2, min: -315.0 max: -18.0
Total elapsed time: 21.91 minutes


Epoch #10
	Results (Train): mean: -284.7 +/- 70.3, min: -315.0, max: 62.0,
	Results (Test): mean: -289.9 +/- 61.2, min: -320.0 max: 62.0
Total elapsed time: 24.30 minutes


Epoch #11
	Results (Train): mean: -267.7 +/- 93.4, min: -320.0, max: 46.0,
	Results (Test): mean: -273.6 +/- 91.5, min: -315.0 max: 30.0
Total elapsed time: 26.71 minutes


Epoch #12
	Results (Train): mean: -279.1 +/- 79.7, min: -315.0, max: 62.0,
	Results (Test): mean: -281.5 +/- 69.4, min: -310.0 max: 14.0
Total elapsed time: 29.13 minutes


Epoch #13
	Results (Train): mean: -280.8 +/- 76.9, min: -315.0, max: 62.0,
	Results (Test): mean: -289.5 +/- 53.7, min: -315.0 max: -27.0
Total elapsed time: 31.54 minutes


Epoch #14
	Results (Train): mean: -263.0 +/- 99.6, min: -320.0, max: 62.0,
	Results (Test): mean: -278.6 +/- 85.6, min: -315.0 max: 46.0
Total elapsed time: 33.97 minutes


Epoch #15
	Results (Train): mean: -262.6 +/- 96.1, min: -315.0, max: 62.0,
	Results (Test): mean: -281.3 +/- 70.1, min: -315.0 max: 46.0
Total elapsed time: 36.55 minutes
======================================
Training finished.
2023-05-03 19:58:10,122 - wandb.wandb_agent - INFO - Cleaning up finished run: ei9fc682
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.006 MB of 0.022 MB uploaded (0.000 MB deduped)wandb: \ 0.022 MB of 0.022 MB uploaded (0.000 MB deduped)wandb: 
wandb: Run history:
wandb:      test_score ‚ñÖ‚ñà‚ñà‚ñÅ‚ñÇ‚ñÖ‚ñÉ‚ñÜ‚ñà‚ñÅ‚ñÖ‚ñÉ‚ñÅ‚ñÑ‚ñÉ
wandb:  test_score_std ‚ñÜ‚ñà‚ñà‚ñÇ‚ñÉ‚ñÖ‚ñÑ‚ñÜ‚ñá‚ñÇ‚ñá‚ñÑ‚ñÅ‚ñÜ‚ñÑ
wandb:     train_score ‚ñà‚ñÉ‚ñÇ‚ñÑ‚ñÉ‚ñÑ‚ñÇ‚ñÇ‚ñÉ‚ñÅ‚ñÉ‚ñÇ‚ñÇ‚ñÑ‚ñÑ
wandb: train_score_std ‚ñà‚ñÉ‚ñÇ‚ñÑ‚ñÉ‚ñÑ‚ñÉ‚ñÅ‚ñÑ‚ñÅ‚ñÑ‚ñÇ‚ñÇ‚ñÖ‚ñÑ
wandb: 
wandb: Run summary:
wandb:      test_score -281.34
wandb:  test_score_std 70.10467
wandb:     train_score -262.55294
wandb: train_score_std 96.07105
wandb: 
wandb: üöÄ View run efficient-sweep-2 at: https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/runs/ei9fc682
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230503_192119-ei9fc682/logs
2023-05-03 19:58:14,736 - wandb.wandb_agent - INFO - Agent received command: run
2023-05-03 19:58:14,736 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 64
	discount_factor: 0.6823087185430049
	epsilon_decay: 0.996386357255287
	frame_repeat: 16
	lr: 0.06869586634259166
	memory_size: 10000
	steps_per_epoch: 4000
2023-05-03 19:58:14,752 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python sweep.py --batch_size=64 --discount_factor=0.6823087185430049 --epsilon_decay=0.996386357255287 --frame_repeat=16 --lr=0.06869586634259166 --memory_size=10000 --steps_per_epoch=4000
wandb: Currently logged in as: ugo1 (fuzzy-enigma). Use `wandb login --relogin` to force relogin
2023-05-03 19:58:19,765 - wandb.wandb_agent - INFO - Running runs: ['4730zxh8']
wandb: Tracking run with wandb version 0.15.1
wandb: Run data is saved locally in /scratch/ugo1/fuzzy-enigma/wandb/run-20230503_195817-4730zxh8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run genial-sweep-3
wandb: ‚≠êÔ∏è View project at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep
wandb: üßπ View sweep at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/sweeps/7trn9eh4
wandb: üöÄ View run at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/runs/4730zxh8
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (<Response [409]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/ext3/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 551, in debounce
    self._maybe_update_config(always=final)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 528, in _maybe_update_config
    self._debounce_config()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 557, in _debounce_config
    self._api.upsert_run(
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run fuzzy-enigma/dqn-hyperparams-sweep/4730zxh8 was previously created and deleted; try a new run name (Error 409: Conflict)
wandb: ERROR Internal wandb error: file data was not synced
Using device=cuda ...
Creating game environment ...
Game environment initialized ...
Creating new agent ...


Epoch #1
	Results (Train): mean: -263.2 +/- 100.3, min: -335.0, max: 62.0,
	Results (Test): mean: -265.4 +/- 91.7, min: -315.0 max: 46.0
Traceback (most recent call last):
  File "/scratch/ugo1/fuzzy-enigma/sweep.py", line 170, in <module>
    agent, game = train_agent(
  File "/scratch/ugo1/fuzzy-enigma/sweep.py", line 109, in train_agent
    wandb.log({
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 394, in wrapper
    return func(self, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1751, in log
    self._log(data=data, step=step, commit=commit)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1532, in _log
    self._partial_history_callback(data, step, commit)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1402, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 585, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 89, in _publish_partial_history
    self._publish(rec)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
2023-05-03 20:01:37,255 - wandb.wandb_agent - INFO - Cleaning up finished run: 4730zxh8
2023-05-03 20:01:37,593 - wandb.wandb_agent - INFO - Agent received command: run
2023-05-03 20:01:37,593 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 32
	discount_factor: 0.17791537498914547
	epsilon_decay: 0.994466476378216
	frame_repeat: 16
	lr: 0.007569982660654473
	memory_size: 20000
	steps_per_epoch: 2000
2023-05-03 20:01:37,597 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python sweep.py --batch_size=32 --discount_factor=0.17791537498914547 --epsilon_decay=0.994466476378216 --frame_repeat=16 --lr=0.007569982660654473 --memory_size=20000 --steps_per_epoch=2000
wandb: Currently logged in as: ugo1 (fuzzy-enigma). Use `wandb login --relogin` to force relogin
2023-05-03 20:01:42,612 - wandb.wandb_agent - INFO - Running runs: ['wfo6k8pf']
wandb: Tracking run with wandb version 0.15.1
wandb: Run data is saved locally in /scratch/ugo1/fuzzy-enigma/wandb/run-20230503_200140-wfo6k8pf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run worthy-sweep-5
wandb: ‚≠êÔ∏è View project at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep
wandb: üßπ View sweep at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/sweeps/7trn9eh4
wandb: üöÄ View run at https://wandb.ai/fuzzy-enigma/dqn-hyperparams-sweep/runs/wfo6k8pf
slurmstepd: error: *** JOB 33008379 ON gr039 CANCELLED AT 2023-05-03T20:18:39 ***
